/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Program;

import Model.Conexion;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author arodi
 */
public class Window extends javax.swing.JFrame {

    /**
     * Creates new form Window
     */
    public Window() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        selectDate = new com.toedter.calendar.JDateChooser();
        dateButton = new javax.swing.JButton();
        insertDateButton = new javax.swing.JButton();
        loadDateButton = new javax.swing.JButton();
        dateIDTextField = new javax.swing.JTextField();
        dateIDLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        dateButton.setText("Show Date");
        dateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateButtonActionPerformed(evt);
            }
        });

        insertDateButton.setText("Insert Date");
        insertDateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertDateButtonActionPerformed(evt);
            }
        });

        loadDateButton.setText("Load Date");
        loadDateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadDateButtonActionPerformed(evt);
            }
        });

        dateIDLabel.setText("Date ID:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(selectDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(dateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(insertDateButton))
                        .addGap(0, 34, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(dateIDLabel)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(dateIDTextField))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(loadDateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(selectDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(dateButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(insertDateButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dateIDLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(dateIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(loadDateButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateButtonActionPerformed
        Date date = selectDate.getDate();
        
        long d = date.getTime();
        
        java.sql.Date SQLdate = new java.sql.Date(d);
        
        JOptionPane.showMessageDialog(null, SQLdate);
    }//GEN-LAST:event_dateButtonActionPerformed

    private void insertDateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertDateButtonActionPerformed
        Conexion con = new Conexion();
        PreparedStatement ps = null;
        
        Date date = selectDate.getDate();
        long d = date.getTime();
        java.sql.Date SQLdate = new java.sql.Date(d);
        
        try{
            Connection connection = con.getConnection();
            
            ps = connection.prepareStatement("insert into date (date) values (?)");
            ps.setDate(1, SQLdate);
            ps.executeUpdate();
            
            JOptionPane.showMessageDialog(null, "Date has been saved sucessfully.");
            
            connection.close();
        }   catch(Exception ex){
            System.err.println("Error, "+ex);
        }
    }//GEN-LAST:event_insertDateButtonActionPerformed

    private void loadDateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadDateButtonActionPerformed
        Conexion con = new Conexion();
        PreparedStatement ps = null;
        ResultSet rs =null;
        
        try{
            Connection connection = con.getConnection();
            
            ps = connection.prepareStatement("SELECT * FROM date WHERE dateID =?");
            ps.setInt(1, Integer.parseInt(dateIDTextField.getText()));
            System.out.println( Integer.parseInt(dateIDTextField.getText()));
            rs = ps.executeQuery();
            
            while(rs.next()){
                selectDate.setDate(rs.getDate("date"));
            }
            
            JOptionPane.showMessageDialog(null, "Date has been loaded sucessfully.");
            
            connection.close();
            
        }   catch(Exception ex){
            System.err.println("Error, "+ex);
        }
    }//GEN-LAST:event_loadDateButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Window().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton dateButton;
    private javax.swing.JLabel dateIDLabel;
    private javax.swing.JTextField dateIDTextField;
    private javax.swing.JButton insertDateButton;
    private javax.swing.JButton loadDateButton;
    private com.toedter.calendar.JDateChooser selectDate;
    // End of variables declaration//GEN-END:variables
}
